### ISSUE TITLE
How does the new create user is going to actor of previous company

### ISSUE THREAD

**Issue by vijaykd21** [dpalinic/public-transportation-services#13]
Hi There,
I am new to lagom. I am having trouble understanding the way `ref` populated. The first time the client was created, and the user was created. But the second time when we try to create the user. How does the system knows to which company ref should be used? If we register another company then how do we Create user under the other company in this case? 
Thanks
Vijay
ARK

**Comment by dpalinic** [comment]
Hello @vijaykd21 ,

1. IdentityState is defined in a way that it holds information about company and company's users:

https://github.com/dpalinic/lagom-jwt-authentication/blob/5525b0deed07a7fa61d7a4637a2a79580fa86d64/identity-impl/src/main/scala/io/digitalcat/publictransportation/services/identity/impl/IdentityState.scala#L8

2. When creating initial company and user, company and user are saved inside of IdentityState.

https://github.com/dpalinic/lagom-jwt-authentication/blob/5525b0deed07a7fa61d7a4637a2a79580fa86d64/identity-impl/src/main/scala/io/digitalcat/publictransportation/services/identity/impl/IdentityServiceImpl.scala#L28

Here we're generating a new company uuid, passing it to ref and with that ref we're creating a new IdentityState state. In the next step, using that company uuid as a ref, you can retrieve a state and alter it.

3. Since you're authenticated now (after company and user is created), company uuid is saved in jwt token and can be retrieved anytime:

https://github.com/dpalinic/lagom-jwt-authentication/blob/5525b0deed07a7fa61d7a4637a2a79580fa86d64/identity-impl/src/main/scala/io/digitalcat/publictransportation/services/identity/impl/IdentityServiceImpl.scala#L90

In this line, we're taking company uuid from jwt token and passing it to ref when creating user so we can fetch state by that company uuid and append user to it.

Hope this helps a bit.

Regards

**Comment by vijaykd21** [comment]
Thanks for the explaination.
Closing as the question was answered.
